Feature/necessary typing
ACRIOS-Systems/dissect.cstruct pull request #7
Opened 2022-04-08 03:51 UTC by Hadatko

2022-04-08 10:03 UTC, qcabrol commented
```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/quentin/aeler/dissect.cstruct
plugins: print-0.3.1
collected 34 items                                                                                                                                                                                                

test_basic.py .......F..........................                                                                                                                                                            [100%]

==================================================================================================== FAILURES =====================================================================================================
____________________________________________________________________________________________________ test_enum ____________________________________________________________________________________________________

    def test_enum():
        d = """
        #define MyEnumVal 4
    
        enum Test16 : uint16 {
            A = 0x1,
            B = 0x6 - MyEnumVal
        };
    
        enum Test24 : uint24 {
            A = 0x1,    // comment, best one
            B = 0x2
        };
    
        enum Test32 : uint32 {
            A = 0x1,
            B = 0x2     // comment
        };
    
        struct test {
            Test16  a16;
            Test16  b16;
            Test24  a24;
            Test24  b24;
            Test32  a32;
            Test32  b32;        // this is a comment, awesome
            Test16  l[2];
        };
    
        struct test_term {
            Test16  null[];
        };
        """
        c = cstruct.cstruct()
        c.load(d, compiled=False)
    
        d = b'\x01\x00\x02\x00\x01\x00\x00\x02\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00'
        a = c.test(d)
    
        assert a.a16.enum == c.Test16 and a.a16 == c.Test16.A
>       assert a.b16.enum == c.Test16 and a.b16 == c.Test16.B
E       assert (<Enum Test16> == <Enum Test16>
E         Use -v to get the full diff and <Test16.Test16_2: 2> == <Test16.B: 6>)
E        +  where <Test16.Test16_2: 2> = <test a16=<Test16.A: 1>, b16=<Test16.Test16_2: 2>, a24=<Test24.A: 1>, b24=<Test24.B: 2>, a32=<Test32.A: 1>, b32=<Test32.B: 2>, l=[<Test16.A: 1>, <Test16.Test16_2: 2>]>.b16
E        +  and   <Test16.B: 6> = <Enum Test16>.B
E        +    where <Enum Test16> = <dissect.cstruct.cstruct.cstruct object at 0x7fa2e4645550>.Test16

test_basic.py:192: AssertionError
============================================================================================= short test summary info =============================================================================================
FAILED test_basic.py::test_enum - assert (<Enum Test16> == <Enum Test16>
========================================================================================== 1 failed, 33 passed in 0.92s ===========================================================================================
```

I suggest you attach a pipeline if possible to the repo to run it on PRs

2022-04-08 10:09 UTC, qcabrol commented
![image](https://user-images.githubusercontent.com/5040536/162414927-21c6ed80-2e17-42fb-af25-73dc6b5e892b.png)
This broke the documentation generation apparently

2022-04-08 10:10 UTC, qcabrol requested changes
![image](https://user-images.githubusercontent.com/5040536/162415043-3026b0e2-ab2c-49c0-9c71-0879606685e1.png)

Broke the documentation generation. Issue might be on our MsgParser.py side but that somehow breaks retro-compatibilty. One side needs fixing.

Actually this was broken by the previous PR, not this one.

2022-04-08 10:10 UTC, qcabrol commented on dissect/cstruct/__init__.py
> +    typeAll,
typeAll ?

2022-04-08 10:16 UTC, qcabrol commented
Regression detected on commit 28f10e0e4bc2ff39c56f9cc96c1f7d5e0668967e

![image](https://user-images.githubusercontent.com/5040536/162416112-dc46a56f-c64a-4f98-bd0f-728347348a06.png)

2022-04-09 13:33 UTC, Hadatko commented on dissect/cstruct/__init__.py
> +    typeAll,
typeAll => i created few predefined types to simpliefied typing. This one i exposed.

2022-04-09 13:34 UTC, Hadatko commented on dissect/cstruct/__init__.py
> +    typeAll,
![image](https://user-images.githubusercontent.com/13130700/162576418-5149f393-923f-40e5-88eb-1de8e191068b.png)

2022-04-11 14:28 UTC, qcabrol approved these changes

2022-04-11 14:29 UTC, qcabrol commented
Solved with changes on the use case code.

2022-04-11 14:29 UTC, merged